### ISSUE TITLE
Just curious: Why are you monckey patching the class instead of the logger instance?

### ISSUE THREAD

**Issue by AugustoPedraza** [lulalala/multi_logger#14]
Inspired on you code, I implemented my own version of the _multilogger_:

```ruby
def add_logger(name, logger)
  name = name.to_s
  raise "'#{name}' is reserved in #{Rails.logger.class} and can not be used as a log accessor name." if Rails.logger.respond_to?(name)

  Rails.logger.define_singleton_method(name.to_sym) do
    logger
  end
end

add_logger(:yodlee, Log4r::Logger['yodlee'])
```

And how I'm using it: `Rails.logger.yodlee.debug("Querying index!!!")`

Thanks in advance!

**Comment by lulalala** [comment]
Hehe I am not even aware that `define_singleton_method` exists. What are the benefits of `define_singleton_method` over monkey patching?

**Comment by AugustoPedraza** [comment]
The mayor benefit was that I don't need know the [class of the logger](https://github.com/lulalala/multi_logger/blob/master/lib/multi_logger.rb#L36-L44).

But I'm not sure if that could have some collateral damage...

**Comment by lulalala** [comment]
Actually I think you got a point. Would you like to do a PR?
